-- =====================================================================
--  Schema: public.tugas_mahasiswa
--  Pengumpulan URL proyek "Mini-Proyek Web Statis" (modul 01–21)
--
--  Dipakai oleh assets/deck.js:
--    POST  → insert { nim_mahasiswa, nomor_kasus, url_proyek }
--    GET   → select nim_mahasiswa, nomor_kasus, url_proyek
--            where nim_mahasiswa in (...) order by created_at desc, id desc
--
--  Cara pakai: Supabase Dashboard → SQL Editor → paste → Run.
--  Aman dijalankan ulang (idempoten) dan TIDAK menghapus data yang ada.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Tabel
-- ---------------------------------------------------------------------
create table if not exists public.tugas_mahasiswa (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  nim_mahasiswa  text        not null,   -- "2702123456" (text agar angka 0 di depan tidak hilang)
  nomor_kasus    text        not null,   -- "01" … "21"
  url_proyek     text        not null    -- "https://github.com/…" / "https://….vercel.app"
);

comment on table  public.tugas_mahasiswa               is 'Riwayat pengumpulan URL proyek mahasiswa. Setiap klik Save = 1 baris baru; ambil baris terbaru per (nim_mahasiswa, nomor_kasus).';
comment on column public.tugas_mahasiswa.nim_mahasiswa is 'NIM BINUS, tepat 10 digit angka.';
comment on column public.tugas_mahasiswa.nomor_kasus   is 'Nomor modul studi kasus, 2 digit: 01–21.';
comment on column public.tugas_mahasiswa.url_proyek    is 'URL repo GitHub / deploy Vercel, wajib http(s)://.';


-- ---------------------------------------------------------------------
-- 2. Samakan tipe kolom jika tabel sudah dibuat sebelumnya lewat dashboard
--    (misal nomor_kasus bertipe int → diubah ke text "01").
--    View rekap (bagian 6) dilepas dulu karena Postgres tidak mengizinkan
--    ubah tipe kolom yang dipakai view. View tidak berisi data; dibuat ulang di bawah.
-- ---------------------------------------------------------------------
drop view if exists public.tugas_mahasiswa_terbaru;

alter table public.tugas_mahasiswa
  alter column created_at    set default now(),
  alter column nim_mahasiswa type text using nim_mahasiswa::text,
  alter column nomor_kasus   type text using lpad(nomor_kasus::text, 2, '0'),
  alter column url_proyek    type text using url_proyek::text;

alter table public.tugas_mahasiswa
  alter column created_at    set not null,
  alter column nim_mahasiswa set not null,
  alter column nomor_kasus   set not null,
  alter column url_proyek    set not null;


-- ---------------------------------------------------------------------
-- 3. Validasi data (berlaku untuk semua role, sama dengan validasi di JS)
-- ---------------------------------------------------------------------
alter table public.tugas_mahasiswa drop constraint if exists tugas_mahasiswa_nim_format;
alter table public.tugas_mahasiswa add  constraint tugas_mahasiswa_nim_format
  check (nim_mahasiswa ~ '^[0-9]{10}$');

alter table public.tugas_mahasiswa drop constraint if exists tugas_mahasiswa_nomor_kasus_format;
alter table public.tugas_mahasiswa add  constraint tugas_mahasiswa_nomor_kasus_format
  check (nomor_kasus ~ '^[0-9]{2}$');

alter table public.tugas_mahasiswa drop constraint if exists tugas_mahasiswa_url_format;
alter table public.tugas_mahasiswa add  constraint tugas_mahasiswa_url_format
  check (url_proyek ~* '^https?://[^[:space:]]+$' and char_length(url_proyek) <= 500);


-- ---------------------------------------------------------------------
-- 4. Index untuk query halaman (filter NIM, urut terbaru)
-- ---------------------------------------------------------------------
create index if not exists tugas_mahasiswa_nim_kasus_terbaru_idx
  on public.tugas_mahasiswa (nim_mahasiswa, nomor_kasus, created_at desc, id desc);


-- ---------------------------------------------------------------------
-- 5. Keamanan: Row Level Security + hak akses
--    anon (halaman publik) hanya boleh INSERT dan SELECT.
--    UPDATE / DELETE ditolak → data lama tidak bisa diubah atau dihapus dari halaman.
-- ---------------------------------------------------------------------
alter table public.tugas_mahasiswa enable row level security;

revoke update, delete, truncate on public.tugas_mahasiswa from anon, authenticated;
grant  select, insert          on public.tugas_mahasiswa to   anon, authenticated;

-- Hapus nama policy lama (jika pernah dibuat dari contoh sebelumnya)
drop policy if exists "anon insert url proyek"        on public.tugas_mahasiswa;
drop policy if exists "anon select url proyek"        on public.tugas_mahasiswa;
drop policy if exists "tugas_mahasiswa_insert_publik" on public.tugas_mahasiswa;
drop policy if exists "tugas_mahasiswa_select_publik" on public.tugas_mahasiswa;

-- INSERT: format data sudah dijaga oleh constraint di bagian 3
create policy "tugas_mahasiswa_insert_publik"
  on public.tugas_mahasiswa
  for insert
  to anon, authenticated
  with check (true);

-- SELECT: dibutuhkan agar URL tersimpan tampil di perangkat lain.
-- Catatan: tanpa login, siapa pun yang memegang anon key bisa membaca SEMUA baris
-- (NIM + URL). Hapus policy ini jika URL cukup tampil di browser yang sama saja.
create policy "tugas_mahasiswa_select_publik"
  on public.tugas_mahasiswa
  for select
  to anon, authenticated
  using (true);


-- ---------------------------------------------------------------------
-- 6. View rekap untuk aslab: URL TERBARU per (NIM, nomor kasus)
--    Hanya untuk dashboard/SQL Editor — tidak dibuka ke anon.
-- ---------------------------------------------------------------------
create or replace view public.tugas_mahasiswa_terbaru
with (security_invoker = true) as
select distinct on (nim_mahasiswa, nomor_kasus)
  nim_mahasiswa,
  nomor_kasus,
  url_proyek,
  created_at as dikumpulkan_pada
from public.tugas_mahasiswa
order by nim_mahasiswa, nomor_kasus, created_at desc, id desc;

revoke all on public.tugas_mahasiswa_terbaru from anon, authenticated;

comment on view public.tugas_mahasiswa_terbaru is 'Rekap penilaian: satu baris per (NIM, modul) berisi URL terakhir yang dikumpulkan.';


-- ---------------------------------------------------------------------
-- Contoh query rekap (jalankan terpisah di SQL Editor)
-- ---------------------------------------------------------------------
-- Semua pengumpulan terbaru, urut modul:
--   select * from public.tugas_mahasiswa_terbaru order by nomor_kasus, nim_mahasiswa;
--
-- Modul yang belum dikumpulkan sama sekali:
--   select lpad(n::text, 2, '0') as nomor_kasus
--   from generate_series(1, 21) n
--   where lpad(n::text, 2, '0') not in (select nomor_kasus from public.tugas_mahasiswa);
--
-- Berapa kali tiap NIM menekan Save per modul:
--   select nim_mahasiswa, nomor_kasus, count(*) as jumlah_save
--   from public.tugas_mahasiswa group by 1, 2 order by 2, 1;
